image: golang:alpine

variables:
  CGO_ENABLED: "0"

test:
  stage: test
  cache:
    paths:
      - .mygo/pkg/mod
  script:
    - GOPATH=$(pwd)/.mygo go test -coverprofile .testCoverage.txt ./...
    - GOPATH=$(pwd)/.mygo go tool cover -func=.testCoverage.txt
